### ISSUE TITLE
音频标题过长显示样式有问题

### ISSUE THREAD

**Issue by gaoyangbuzai** [airzhanglin/wechatPlayer#1]
音频标题过长显示样式有问题
![微信截图_20190423141511](https://user-images.githubusercontent.com/25842042/56558750-482da800-65d2-11e9-9217-e52fdac10832.png)

**Comment by airzhanglin** [comment]
> 音频标题过长显示样式有问题
> ![微信截图_20190423141511](https://user-images.githubusercontent.com/25842042/56558750-482da800-65d2-11e9-9217-e52fdac10832.png)

已修改，请安装1.1.0版本
